import os
import json
import re
from src.retrieval import Retriever
from src.llm import LLMGenerator
from src.utils import config

class RAGService:
    """
    This class orchestrates the entire RAG pipeline. It manages the Retriever and LLM Generator,
    handles the loading of company data, processes user queries, and evaluates the generated answers.
    """
    def __init__(self):
        self.generator = LLMGenerator()
        self.retriever = Retriever() 
        
        self.current_ticker = None
        self.current_year = None

    def load_company_data(self, ticker: str, year: str, report_type: str) -> None:
        """
        Loads the FAISS index and chunks for a specific company and fiscal year.
        This method must be called before asking any questions about the company.
        """
        # Get the file paths for the requested company data
        paths = config.get_paths(ticker, report_type, year)
        # Check if the required data files exist before attempting to load
        if not os.path.exists(paths["index"]) or not os.path.exists(paths["chunks"]):
            raise FileNotFoundError(f"❌ No data found for {ticker} ({year}). Please run indexing first.")
        
        # Load the new data into the Retriever without reloading the models
        self.retriever.load_data(paths["index"], paths["chunks"])
        
        self.current_ticker = ticker
        self.current_year = year
        print(f"✅ Data loaded for {ticker} ({year}). The analyst is ready.")

    def evaluate_completeness(self, query: str, context_chunks: list, answer: str) -> dict:
        """
        Uses the LLM as a Judge to evaluate if the generated answer fully covers the user's query.
        """
        try:
            context_str = "\n\n".join([str(chunk) for chunk in context_chunks])
        except:
            context_str = str(context_chunks)

        judge_prompt = f"""You are an impartial expert evaluator. Your task is to evaluate the COMPLETENESS of a response generated by a financial AI assistant.

        [USER QUERY]: {query}
        [RETRIEVED CONTEXT]: {context_str}
        [GENERATED ANSWER]: {answer}

        EVALUATION CRITERIA:
        Does the generated answer completely and directly address all parts of the user's query based ON THE CONTEXT provided?
        - Score 1: Irrelevant, completely wrong, or hallucinates data not in the context.
        - Score 3: Addresses the main point but misses secondary details asked in the query.
        - Score 5: Highly comprehensive, accurate to the context, and addresses every aspect.

        OUTPUT FORMAT:
        Return ONLY a valid JSON object. No markdown, no intro text.
        {{
            "score": 5,
            "reasoning": "Brief explanation"
        }}
        """
        try:
            # FIXED: We now use the new dedicated method to bypass the analyst persona
            raw_eval = self.generator.generate_raw_prompt(judge_prompt)
            
            # Clean up the output to remove any Markdown backticks (```json ... ```)
            clean_json = re.sub(r"```json|```", "", raw_eval).strip()
            return json.loads(clean_json)
            
        except Exception as e:
            print(f"LLM Judge Error: {e}")
            return {"score": 0, "reasoning": "Unable to evaluate the response due to an internal error."}

    def ask(self, query: str, history: list = None, initial_k: int = 20, final_k: int = 5) -> dict:
        """
        This method processes a user's query by first retrieving relevant chunks of information from the loaded company data, 
        then generating an answer using the LLM, and finally evaluating the completeness of the answer with respect to the query and retrieved context. 
        It returns a dictionary containing both the generated answer and its evaluation.
        """
        # Check if the retriever has data loaded before attempting to search
        if not self.retriever:
            return {
                "answer": "❌ Error: You must upload company data first.",
                "evaluation": {"score": 0, "reasoning": "Mancano i dati vettoriali."}
            }
            
        top_chunks = self.retriever.search(query, initial_k=initial_k, final_k=final_k)
        
        if not top_chunks:
            return {
                "answer": "I did not find any relevant information in the documents for this question.",
                "evaluation": {"score": 1, "reasoning": "Nessun contesto pertinente trovato nei documenti SEC."}
            }
            
        # Generation of the answer (THE ANALYST)
        answer = self.generator.generate_answer(query, top_chunks, history=history)
        
        # Evaluation of the answer's completeness (THE JUDGE)
        evaluation = self.evaluate_completeness(query, top_chunks, answer)
        
        # Return both the generated answer and its evaluation as a dictionary
        return {
            "answer": answer,
            "evaluation": evaluation
        }